### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by grassjelly** [SofaPirate/AsciiMassage#12]
Hi,

Thanks for writing this nice library. I'm planning to use this on my open source project and I'm wondering what the license is like. I saw that there's a deleted MIT license in this commit https://github.com/SofaPirate/AsciiMassage/commit/acdc201ae6b94ee69094d7b7fdc1670e624c9ea2 . I'm willing to send a PR to add the license of your liking. Thank you!

**Comment by thomasfredericks** [comment]
Yes it is an MIT license. It was accidentally deleted when things were moved around. It was added back.
