### ISSUE TITLE
buffer size does not give the proper size

### ISSUE THREAD

**Issue by thomasfredericks** [SofaPirate/AsciiMassage#4]
A 0 is written at the end of the message, but this should not count in the message size.

Serial.write(outbound.buffer(),outbound.size()-1);

**Comment by sofian** [comment]
Sounds weird.  Having to writeSerial.write(outbound.buffer(),outbound.size()-1);
... Is confusing.
I think the size should be the total number of bytes

**Comment by thomasfredericks** [comment]
We should not be terminating with a 0 with AsciiMassagePacker::endPacket()

```
void AsciiMassagePacker::endPacket()
{
  write('\n');
  write(0);

}
```

But then, we should convert the char* buffer to uint8_t  to make sure the string version of Print.h cannot be called.

From Print.h:
```
   virtual size_t write(uint8_t) = 0;
    size_t write(const char *str) {
      if (str == NULL) return 0;
      return write((const uint8_t *)str, strlen(str));
    }
    virtual size_t write(const uint8_t *buffer, size_t size);
    size_t write(const char *buffer, size_t size) {
      return write((const uint8_t *)buffer, size);
    }
```

**Comment by thomasfredericks** [comment]
Ok, this was solved by changing the internal buffer type from char to uint8_t.
